# Lock down dist to ensure that builds run on a distribution that supports oraclejdk8
dist: trusty
language: java
jdk:
  - oraclejdk8
install:
  - gem install bundler
  - bundle install
script: buildr clean package
git:
  depth: 10
